from reportlab.platypus import (
    SimpleDocTemplate,
    Table,
    TableStyle,
    Paragraph,
    Spacer
)

from reportlab.lib import colors

from reportlab.lib.styles import getSampleStyleSheet

from reportlab.lib.units import inch

@app.route("/download-report")
def download_report():

    data = calculate_health()

    buffer = io.BytesIO()

    doc = SimpleDocTemplate(buffer)

    styles = getSampleStyleSheet()

    elements = []

    elements.append(
        Paragraph(
            "<b>Transformer Condition Report</b>",
            styles["Heading1"]
        )
    )

    elements.append(Spacer(1,20))

    tableData = [

        ["Transformer Type",data["transformer_type"]],

        ["Health",data["health"]],

        ["Temperature",f'{data["temperature"]} °C'],

        ["Current",f'{data["current"]} A'],

        ["Voltage",f'{data["voltage"]} V'],

        ["Frequency",f'{data["frequency"]} Hz'],

        ["Power Factor",data["power_factor"]],

        ["Smoke",data["smoke"]]

    ]

    table = Table(tableData)

    table.setStyle(TableStyle([

        ("BACKGROUND",(0,0),(-1,0),colors.grey),

        ("GRID",(0,0),(-1,-1),1,colors.black),

        ("BACKGROUND",(0,0),(0,-1),colors.lightgrey),

        ("BOTTOMPADDING",(0,0),(-1,-1),10)

    ]))

    elements.append(table)

    elements.append(Spacer(1,25))

    elements.append(

        Paragraph(

        "<b>System Authentication</b>",

        styles["Heading2"]

        )

    )

    elements.append(

        Paragraph(

        "Generated by Intelligent Transformer Health Analytics Platform (ITHAP)",

        styles["BodyText"]

        )

    )

    elements.append(

        Paragraph(

        "Department of Electrical Engineering",

        styles["BodyText"]

        )

    )

    elements.append(

        Paragraph(

        "National University of Technology (NUTECH)",

        styles["BodyText"]

        )

    )

    elements.append(

        Paragraph(

        "Developed By",

        styles["Heading3"]

        )

    )

    elements.append(

        Paragraph(

        "Muhammad Ahmed Khokar<br/>Muhiba Shakeel<br/>Kiran Batool",

        styles["BodyText"]

        )

    )

    doc.build(elements)

    pdf = buffer.getvalue()

    buffer.close()

    return send_file(

        io.BytesIO(pdf),

        as_attachment=True,

        download_name="Transformer_Report.pdf",

        mimetype="application/pdf"

    )